---- 建立数据库
--CREATE DATABASE newssystem
--建立类别表
--CREATE TABLE	category
--(
--    id int identity(1,1) primary key,
--    [name] varchar(20) not null

--)
----建立新闻表
--create table news
--(
--   id int identity(1,1) primary key,
--   title varchar(100) not null,
--   [content] text not null,
--   createTime datetime not null,
--   caId int

--)
----建立评论表
--create table comment
--(
--    id int identity(1,1) primary key,
--    [content] text not null,
--    createTime datetime not null,
--    userIp varchar(15)  not null,
--    newsId int
--)
--select *from category 
----delete from category where id =16
----insert into category (name) values('娱乐新闻')delete category where id=2--')
----insert into news (title,content,caId ) values ('赵薇','生孩子','16')
--select * from news

--select * from comment
